apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-civo
  namespace: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager-webhook-civo
    repoURL: https://charts.okteto.com
    targetRevision: 0.3.1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
