apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-config
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: authentik-config/
    repoURL: git@github.com:DarrellTang/argocd-civo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
