apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-prod
  namespace: argocd
spec:
  secretName: wildcard-cert-prod
  commonName: "*.darrellandranae.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - "*.darrellandranae.com"
