apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`authentik.darrellandranae.com`)
      priority: 10
      services:
        - name: authentik
          port: 80
  tls:
    secretName: wildcard-cert-staging
